# NumPy Lecture

### Imports

In [1]:
import numpy as np

## What is an array? 

It is a super charged array

In [4]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [5]:
my_array = np.array([1, 2, 3, 4, 5])

In [6]:
my_list = [1, 2, 3, 4, 5]

## Accessing a list

In [8]:
list_of_lists = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [10]:
list_of_lists[1][1]

5

## Accessing an NP array

Matrix[row, column]

In [12]:
matrix= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [13]:
matrix[1,1]

5

## We can access multiple elements in an array using slicing, like we did with lists

In [14]:
my_list[1:]

[2, 3, 4, 5]

In [15]:
my_array[1:]

array([2, 3, 4, 5])

In [17]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
matrix[1:,:2]

array([[4, 5],
       [7, 8]])

## Indexing with a boolean sequence, also known as a boolean mask

In [18]:
my_array

array([1, 2, 3, 4, 5])

In [19]:
mask= [False, True, False, True, False]

In [20]:
my_array[mask]

array([2, 4])

## Vectorized Operations

### Adding 1 to every element of a list
### fails to just say list +1

In [21]:
my_list

[1, 2, 3, 4, 5]

In [ ]:
my_list + 1 # it doesn't work like this

### Must use for loop with lists

In [24]:
list_with_one_added = []
for i in my_list:
    list_with_one_added.append(i+1)
    
list_with_one_added

[2, 3, 4, 5, 6]

## But with NumPy

In [25]:
my_array

array([1, 2, 3, 4, 5])

In [26]:
my_array + 1

array([2, 3, 4, 5, 6])

### Because it is a nondestructive operation, the result of the Vectorized Numpy operation must be stored somewhere or it won't exist for future reference

In [27]:
my_array % 2

array([1, 0, 1, 0, 1])

In [28]:
my_array * 2

array([ 2,  4,  6,  8, 10])

In [32]:
my_array % 2

array([1, 0, 1, 0, 1])

In [29]:
my_array > 2

array([False, False,  True,  True,  True])

### Look at this boolean mask trick

In [30]:
my_array[my_array > 2]

array([3, 4, 5])

### We can use this boolean array to get back values that return True

In [31]:
my_array[my_array % 2 == 0]

array([2, 4])

In [33]:
np.zeros(3)

array([0., 0., 0.])

In [34]:
np.zeros((3,3,))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones(3)

array([1., 1., 1.])

In [36]:
np.full(3,15) # one dimensional array with 15's in each slot

array([15, 15, 15])

In [37]:
np.full((3,3), 15) # two dimensional array with 15's in each slot

array([[15, 15, 15],
       [15, 15, 15],
       [15, 15, 15]])

## np.arange()

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
my_array.mean()

3.0

In [41]:
my_array.std()

1.4142135623730951

In [42]:
matrix.mean()

5.0

In [43]:
matrix.std()

2.581988897471611