In [162]:
import numpy as np

In [53]:
a1 = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

### One

In [54]:
a1 < 0

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [112]:
a1[a1 < 0]

array([-2, -1, -6, -7])

In [56]:
print("There are",np.sum(a1<0),"negative numbers in the array")

There are 4 negative numbers in the array


### Two

In [57]:
print("There are",np.sum(a1>0),"positive numbers in the array")

There are 5 positive numbers in the array


### Three

In [58]:
a1 % 2 == 0

array([ True,  True,  True, False,  True, False,  True,  True,  True,
        True, False, False])

In [59]:
c = a1%2==0

In [60]:
print("There are",np.sum(c>0),"positive, even numbers in the array")

There are 8 positive, even numbers in the array


### Four

In [61]:
d = a1 + 3

In [62]:
print("There are",np.sum(d>0),"positive numbers in the array if 3 is added to each")

There are 10 positive numbers in the array if 3 is added to each


## Five

In [63]:
a1 ** 2


array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [64]:
e = a1 ** 2
print(np.mean(e))
print(np.std(e))

74.0
144.0243035046516


In [65]:
print('The new mean and standard deviation for our array are', np.mean(e),'&',round(np.std(e),2))

The new mean and standard deviation for our array are 74.0 & 144.02


## Six

In [66]:
centering = lambda x: x - x.mean()
f = centering(a1)

In [67]:
print('The centered array is as below\n',f)

The centered array is as below
 [  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


## Seven

In [68]:
# z-score is a means of standardizing standard deviations between any and all 
# samples for scientiffic analysis to determine significance of findings
z = np.mean(a1)/np.std(a1)

In [69]:
print('The z score for the array is',round(z,3))

The z score for the array is 0.372


## Eight

### Setup 1

In [161]:
a2 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [97]:
sum_of_a2 = np.sum(a2)
print('Setup 1 number 1',sum_of_a2)

Setup 1 number 1 55


In [98]:
min_of_a2 = np.min(a2)
print('Setup 1 number 2',min_of_a2)

Setup 1 number 2 1


In [99]:
max_of_a2 = np.max(a2)
print('Setup 1 number 3',max_of_a2)

Setup 1 number 3 10


In [100]:
mean_of_a2 = np.mean(a2)
print('Setup 1 number 4',mean_of_a2)

Setup 1 number 4 5.5


In [101]:
product_of_a2 = np.product(a2)
print('Setup 1 number 5',product_of_a2)

Setup 1 number 5 3628800


In [102]:
squares_of_a2 = np.square(a2)
print('Setup 1 number 6',squares_of_a2)

Setup 1 number 6 [  1   4   9  16  25  36  49  64  81 100]


In [105]:
odds_in_a2 = np.mod(a2,2)!=0
print('Setup 1 number 7',np.array(a2)[odds_in_a2])

Setup 1 number 7 [1 3 5 7 9]


In [104]:
evens_in_a2 = np.mod(a2,2)==0
print('Setup 1 number 8',np.array(a2)[evens_in_a2])

Setup 1 number 8 [ 2  4  6  8 10]


### Setup 2

In [114]:
b1 = [
    [3,4,5],
    [6,7,8]
]
b2 = np.array(b1)

exercise 1

In [118]:
# summing each item in the list of lists
sum_of_b = 0
for row in b1:
    sum_of_b += sum(row)
print(sum_of_b)

33


In [119]:
print(b2.sum())

33


exercise 2

In [120]:
min_of_b = min(b1[0]) if min(b1[0]) <= min(b1[1]) else min(b1[1])  
print(min_of_b)

3


In [121]:
print(b2.min())

3


exercise 3

In [122]:
max_of_b = max(b1[0]) if max(b1[0]) >= max(b1[1]) else max(b1[1])
print(max_of_b)

8


In [123]:
print(b2.max())

8


exercise 4

In [124]:
print(b2.mean())

5.5


exercise 5

In [126]:
print(b2.prod())

20160


exercise 6

In [129]:
print(b2 ** 2)

[[ 9 16 25]
 [36 49 64]]


exercise 7

In [132]:
print(b2[b2 % 2 != 0])

[3 5 7]


exercise 8

In [134]:
print(b2[b2 % 2 == 0])

[4 6 8]


exercise 9

In [138]:
print(np.shape(b2))

(2, 3)


exercise 10

In [140]:
print(np.transpose(b2))

[[3 6]
 [4 7]
 [5 8]]


exercise 11

In [142]:
print(b2.reshape(1,6))

[[3 4 5 6 7 8]]


exercise 12

### Setup 3

In [144]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c1 = np.array(c)

Exercise 1

In [146]:
print(c1.min(), c1.max(), c1.prod(), c1.sum())

1 9 362880 45


Exercise 2

In [148]:
c1.std()

2.581988897471611

Exercise 3

In [149]:
c1.var()

6.666666666666667

Exercise 4

In [151]:
c1.shape

(3, 3)

exercise 5

In [154]:
c1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

exercise 6

In [156]:
np.dot(c1,c1)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

exercise 7

In [157]:
np.sum(c1 * c1.transpose())

261

exercise 8

In [158]:
np.prod(c1 * c1.transpose())

131681894400